### ISSUE TITLE
Failure on fly.io

### ISSUE THREAD

**Issue by berkkarahan** [fspoettel/linkding-on-fly#9]
Hi, followed the guide exactly. After I deploy to fly.io and go to live logs i see that;

```
2024-03-27T14:54:52.830 app[3287965c063418] ... [info] ERROR Error: failed to spawn command: /scripts/run.sh: No such file or directory (os error 2)
```

**Comment by berkkarahan** [comment]
Seeing this with `flyctl deploy --no-cache` as well;

![image](https://github.com/fspoettel/linkding-on-fly/assets/18385565/52a5ee27-78cb-4b32-bed8-f7c88f0ae491)

**Comment by fspoettel** [comment]
Hey @berkkarahan, thanks for the report. This is odd 🤔 - I'll try to reproduce.

**Comment by fspoettel** [comment]
I just went through the README again to deploy a new instance (not using the env substitution) and could not reproduce the issue. 😕

**Comment by berkkarahan** [comment]
@fspoettel , forgot to tell this was on windows. I might give it a try with WSL ubuntu.

**Comment by fspoettel** [comment]
If you do so, lmk how it goes. I'm currently lacking access  to a Win env so can't test this.

**Comment by berkkarahan** [comment]
wsl deployment was 👌🏻
